# Plain, short English words used to build memorable paste slugs
# ("river-quiet-falcon"). No secrecy is implied by this list: it exists
# purely to make links easier to read and say out loud.
WORDS = [
    "able", "acid", "acorn", "actor", "adept", "agile", "alarm", "alert",
    "algae", "alley", "almond", "alpha", "amber", "anchor", "angel", "angle",
    "ankle", "apple", "apron", "arbor", "arch", "arena", "argue", "arrow",
    "art", "ash", "aspen", "atlas", "atom", "aurora", "autumn", "avenue",
    "azure", "badge", "bagel", "baker", "balm", "bamboo", "banjo", "barn",
    "basil", "basin", "basket", "beach", "beacon", "beam", "bean", "bear",
    "beaver", "beech", "bell", "belt", "bench", "berry", "birch", "bird",
    "bison", "blade", "blanket", "blaze", "blimp", "block", "bloom", "blue",
    "boat", "bolt", "bone", "book", "boot", "boulder", "bowl", "box",
    "branch", "brass", "bread", "breeze", "brick", "bridge", "brook", "broom",
    "brown", "brush", "bubble", "bucket", "buckle", "buffalo", "bulb", "bunny",
    "burrow", "cabin", "cable", "cactus", "cake", "calm", "camel", "camp",
    "canal", "candle", "canoe", "canyon", "cape", "cargo", "carpet", "carrot",
    "castle", "cave", "cedar", "cellar", "chalk", "charm", "chart", "cheese",
    "cherry", "chess", "chestnut", "chime", "chip", "clam", "clay", "cliff",
    "cloak", "clock", "cloud", "clover", "coal", "coast", "cobalt", "cocoa",
    "coconut", "comet", "compass", "copper", "coral", "corn", "cotton", "couch",
    "cove", "coyote", "crab", "crane", "crater", "cream", "creek", "cricket",
    "crimson", "crown", "crystal", "cub", "cup", "current", "cypress", "daisy",
    "dawn", "deer", "delta", "desert", "diamond", "dock", "dolphin", "dove",
    "dragon", "drift", "drum", "dune", "dusk", "eagle", "earth", "echo",
    "eel", "elbow", "elder", "elk", "elm", "ember", "emerald", "engine",
    "falcon", "fawn", "feather", "fence", "fern", "field", "finch", "fire",
    "fjord", "flame", "flare", "flint", "flower", "flute", "fog", "forest",
    "forge", "fox", "frame", "frost", "garden", "gate", "gecko", "gem",
    "ginger", "glacier", "glade", "glass", "glow", "goat", "gold", "goose",
    "grain", "granite", "grape", "grass", "gravel", "green", "grove", "gull",
    "gully", "hammer", "harbor", "hare", "harp", "hawk", "hazel", "heron",
    "hickory", "hill", "holly", "honey", "horizon", "horn", "horse", "husky",
    "ice", "indigo", "inlet", "iris", "iron", "island", "ivory", "ivy",
    "jade", "jasmine", "jelly", "juniper", "kayak", "kelp", "kettle", "kite",
    "knot", "lagoon", "lake", "lamp", "lantern", "larch", "lark", "laurel",
    "leaf", "ledge", "lemon", "lily", "lime", "linen", "lion", "lizard",
    "loft", "lotus", "lumber", "lynx", "magnet", "magnolia", "maple", "marble",
    "marsh", "meadow", "melon", "mesa", "meteor", "mint", "mist", "mitten",
    "moon", "moose", "moss", "moth", "mountain", "mouse", "mulberry", "mushroom",
    "myrtle", "needle", "nest", "night", "nova", "oak", "oasis", "ocean",
    "olive", "onyx", "opal", "orange", "orbit", "orchard", "orchid", "osprey",
    "otter", "owl", "oyster", "paddle", "palm", "panda", "panther", "paper",
    "path", "peach", "peak", "pearl", "pebble", "pecan", "pelican", "pepper",
    "petal", "pigeon", "pillow", "pine", "planet", "plaza", "plum", "pond",
    "poplar", "poppy", "prairie", "prism", "puddle", "pumpkin", "quail", "quartz",
    "quilt", "rabbit", "raccoon", "rain", "raven", "reed", "reef", "resin",
    "ridge", "river", "robin", "rock", "root", "rose", "rover", "ruby",
    "sage", "sail", "salmon", "sand", "sapling", "sapphire", "scarf", "seal",
    "shadow", "shale", "shark", "shell", "shore", "shrub", "silver", "skiff",
    "sky", "slate", "sloth", "snow", "sorrel", "sparrow", "spark", "spring",
    "spruce", "squirrel", "star", "stone", "stork", "storm", "stream", "summit",
    "sun", "swallow", "swan", "sycamore", "tangerine", "thistle", "thunder", "tide",
    "tiger", "timber", "topaz", "torch", "tortoise", "trail", "trout", "tulip",
    "tundra", "turtle", "twig", "umbrella", "valley", "vapor", "velvet", "vine",
    "violet", "vista", "walnut", "walrus", "wave", "well", "whale", "wheat",
    "willow", "wind", "wing", "winter", "wolf", "wood", "wren", "yarrow",
    "yew", "zephyr",
]
