# Generated by Django 5.2.16 on 2026-07-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_paste_is_expired_alter_paste_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='is_expired',
        ),
    ]
